### ISSUE TITLE
"Please check your internet connection"

### ISSUE THREAD

**Issue by Novabella** [teamradish/TRTwitchPlaysBot#13]
![image](https://user-images.githubusercontent.com/17990493/86528808-680c5d00-be60-11ea-975a-0de1a99f1d68.png)
I'm not sure exactly where I went wrong here. It's just refusing to connect to twitch.

**Comment by tdeeb** [comment]
It looks like it's constantly connecting and reconnecting since the reconnect attempts are being reset. A few things to look out for:

* Is TRBot allowed through your firewall?
* Does the channel you're attempting to connect to exist?
* Are you running on ethernet or wifi?
* Is there some sort of block on Twitch (hosts/pi-hole)?

**Comment by tdeeb** [comment]
@Novabella Any updates on this issue?

**Comment by tdeeb** [comment]
Closed due to inactivity. If the problem arises again, please file a new issue.
