### ISSUE TITLE
PCSX2 Vjoy Config Issue

### ISSUE THREAD

**Issue by TwitchPlaysSpeedruns** [teamradish/TRTwitchPlaysBot#31]
Apologies if this is the incorrect place to put this. I'm very new to all of this so bear with me please.

I have been using this code to host a TwitchPlays speedrunning channel playing ps1 games using EPSXE (Final Fantasy 7, 8 and 9). We've also ran n64 games without issue. Im trying to get ff10 ready for the players but I am running into issues configuring inputs. I am running latest version of both TRBot and PCSX2 on windows 10. https://www.twitch.tv/twitchplaysspeedruns

Once Vjoy launches the vjoy monitor shows the following. 
![Vjoy1](https://user-images.githubusercontent.com/67460568/91845174-a0f26380-ec50-11ea-8221-b2d18cdd5d75.JPG)

Once I then launch TRBot several inputs appear to be pressed continuously. (Z, Rz, s10 and sl1)
![vjoy2](https://user-images.githubusercontent.com/67460568/91845414-06465480-ec51-11ea-8fbb-e2a42bdedbcd.JPG)

When I then try to configure any input through PCSX2 it will only register every input as Z-. If I type any input in to chat it will always be read as Z-
![image](https://user-images.githubusercontent.com/67460568/91845683-781e9e00-ec51-11ea-8fd9-a494e3e1fe27.png)

If I disable those axis and try inputs they all register as Hat Switch N.

![image](https://user-images.githubusercontent.com/67460568/91861225-7c07eb80-ec64-11ea-8a3e-7ddd57f52dca.png)

I have successfully set up !Play to run with the code and play PS2 games but PCSX2 is by far the most reliable emulator for ps2.

Again, apologies if not appropriate to ask here. Also its likely I've missed something very basic due to stupidity. But does anyone have any idea what could be happening? Thank you so much for sharing your amazing work =)

**Comment by TwitchPlaysSpeedruns** [comment]
If I disable those axis and try inputs they all register as Hat Switch N.

![image](https://user-images.githubusercontent.com/67460568/91851571-54f6ed00-ec57-11ea-9d66-5de05396836b.png)

**Comment by tdeeb** [comment]
Thanks for sharing your awesome channel; I love the overlay!

This is an issue with the LilyPad plugin on PCSX2, as it doesn't correctly recognize the vJoy buttons for some reason, possibly due to how old it is. Here are a few options I suggest looking into:

1. Edit the config file by hand (located in **inis/LilyPad.ini**) to map the inputs. I haven't tried this myself, so I can't guarantee it will work.
2. Use an older version of LilyPad or a different input plugin.
3. Change the values of the buttons in `PS2Console.ButtonInputMap` and recompile TRBot.
4. Compile the OnePad 1.3.0 input plugin for Windows and attempt to use it - unsure if possible.
5. Alternatively, install a GNU/Linux distro on a computer or VM and run PCSX2 with the OnePad 1.3.0 input plugin. TRBot's inputs work with no issues there.

Let me know if you have any other questions.

**Comment by TwitchPlaysSpeedruns** [comment]
Thank you for a quick response and your advice. Ill do my best to make it work. 

That's great you visited the channel =) As a side note our next game top speedrun will likely be Super Mario RPG, I see you guys have previous experience. 

Also I have had issues getting the code to play nice with certain PC games, namely Final Fantasy 7 (wanted a modded run). Hopefully your previous suggestions will resolve that issue too. 

Thanks again for this amazing project. I quickly abandoned my own python code once I found this git and all its amazing features. Ill update you with my progress soon.

**Comment by tdeeb** [comment]
In my experience, PC games are hit-or-miss (mostly miss):
- Some games don't support input remapping at all or let you choose the controller to play with. Sometimes it's possible to remap with [x360ce](http://www.x360ce.com/), but it doesn't work for all games.
- Controller detection - some games support only XInput or a few controllers, commonly Xbox 360.
- Some games choose only the first controller returned by the OS. This is often not one of the virtual controllers used by TRBot.

PC games on Steam or using the SDL library are more likely to work since you can define your own mappings for the virtual controllers (provided the game is utilizing their input libraries).

**Comment by TwitchPlaysSpeedruns** [comment]
I couldnt possibly advise you guys on anything =p But id certainly have some suggestions. I have tried using (with no success on ff7) Joytokey for pc games which sends the controller inputs back as kb inputs. Sometimes works, sometimes doesnt.

Its interesting how my player base uses your code and features. 

-They use !groupbet to decide on gameplay decisions or on whose turn it is to play. (players value credits more than you would believe)
-They set it up so people can play using only emotes using the !addsyn function if they want. 
-We use player 1 and 2 controllers to run races on 2 separate emulators on the same stream. (Pokemon race coming soon)
-I have also implemented autohotkey scripts mapped to controller inputs to do certain things. 

The player base was exceptionally quickly to learn the macros system. I was shocked. 1 week in they were teaching me things. 

Any suggestions I might add would probably be based on how my players use the code, but if I think of anything good Ill add it in the appropriate place.

**Comment by TwitchPlaysSpeedruns** [comment]
We also have a discord where people ask for features all the time https://discord.com/invite/6jYgJ2v. Although since I've started using this code, they've not been asking for much =p

**Comment by tdeeb** [comment]
File suggestions as [new issues](https://github.com/teamradish/TRTwitchPlaysBot/issues). I will set up an issue template to make this easier. Feel free to submit a pull request to integrate any additions on your fork upstream.

That is some very creative use of the bot commands! The last one in particular is very interesting; the experimental PC virtual controller works similarly by running `xdotool` with arguments corresponding to the inputs pressed until that point.

**Comment by TwitchPlaysSpeedruns** [comment]
I'm an amateur coder at best and I've little to no idea how to use github, but ill try and add it to my list of things to learn and see if we can help each other out. I forked as I was gonna try and customise the code but thats a long ways away as I have no experience with c#. I could help with your documentation. I couldnt find a complete source on how to use all the ! commands. Ive learned them all now and could make a little doc for you guys if you like. 
*Ive updated my previous comment with more info
