### ISSUE TITLE
[BUG] Multipress on long input strings

### ISSUE THREAD

**Issue by mrmwiebe** [teamradish/TRTwitchPlaysBot#45]
Noticing in twitch plays necrodancer that sometimes inputs that come in too close together will actually register as a combo key press.  I understand why that would happen, but it might be nice to have a mode or option that will wait until the last key sequence is complete before moving on to the next message.

Here's an explanation in chat:

<img width="453" alt="firefox_2020-12-22_12-39-13" src="https://user-images.githubusercontent.com/2886831/102931311-031ae280-4453-11eb-985d-30efa034bf51.png">
<img width="472" alt="firefox_2020-12-22_12-41-01" src="https://user-images.githubusercontent.com/2886831/102931314-03b37900-4453-11eb-876f-6688469f35e0.png">

**Comment by tdeeb** [comment]
Each input sequence is handled in its own thread. In the case above, "uurr" and "dduu" are each handled in their own threads, totaling two threads. If they both come in at the same time, either "u" or "d" will be carried out first, with any of the inputs thereafter occuring in any order, in most likely less than 1 frame of difference.

What I believe you are proposing is an option to have TRBot process only one input sequence at a time. So if "uurr" is input followed by "dduu", it waits for "uurr" to finish before then executing "dduu" - do I have this correct?

This won't work well for very long inputs on other types of games, and if there are many input sequences in the queue, it could take a long time to execute them all. However, I could argue that that's perfectly fine since a specific configuration can limit the impact. Overall though, I feel the Democracy mode outlined in https://github.com/teamradish/TRTwitchPlaysBot/issues/44 may be a better solution - please correct me if I'm wrong.

For reference, [here's](https://github.com/teamradish/TRTwitchPlaysBot/blob/master/TRBot/TRBot.Misc/InputHandler.cs#L126) the code carrying out the inputs.

**Comment by mrmwiebe** [comment]
Yes that was what I was proposing, "uurr" would wait for "dduu" etc, but that's a good point and I think democracy would solve this issue and would be better overall.  Thanks! :)
